# Generated by Django 2.2.7 on 2019-11-17 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('data', models.TextField(help_text='글의 내용을 입력하세요.', max_length=1000000)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Country')),
                ('genre', models.ManyToManyField(help_text='글의 장르를 고르세요.', to='catalog.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='nation',
            field=models.ManyToManyField(help_text='국가를 고르세요.', to='catalog.Nation'),
        ),
    ]
